# Generated by Django 4.2.1 on 2023-06-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('edad', models.SmallIntegerField()),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
    ]
