# Generated by Django 4.2.1 on 2023-06-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('arte', models.CharField(max_length=100)),
                ('argumento', models.CharField(max_length=1000)),
            ],
        ),
    ]
